---
# Argument specs does not generate the default fields, so we need to  define them here
# AND keep that in sync with argument_specs.yml code for documentation.

- name: Set default fields
  ansible.builtin.set_fact:
    _protocol: "{{ item.protocol | default('tcp') }}"
    _rule: "{{ item.rule | default('allow') }}"

- name: Add rule
  community.general.ufw:
    port: "{{ item.port }}"
    proto: "{{ _protocol }}"
    rule: "{{ _rule }}"
    from_ip: "{{ item.from_ip | default(omit) }}"

- name: Debug firewall rule addition
  ansible.builtin.debug:
    msg: >-
      Added {{ _rule }} rule for {{ _protocol }} port {{ item.port }}
      {% if item.from_ip is defined %}from IP {{ item.from_ip }}{% endif %}
