---
- name: Ensure nftables override directory exists
  ansible.builtin.file:
    path: "{{ firewall_nftables_extra_config_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
