---
- name: Reset UFW to installation defaults
  community.general.ufw:
    state: reset
  when: firewall_reset_before | bool

# Default policies:
# - Incoming traffic is DENIED (=DROPPED) by default
# - Outgoing traffic is ALLOWED by default
- name: Set default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }

- name: Allow all traffic from local networks
  community.general.ufw:
    rule: allow
    from_ip: "{{ item }}"
    proto: any
  loop: "{{ firewall_whitelisted_networks }}"
  when: firewall_whitelisted_networks is defined

# ICMP is allowed by default

# - name: Additional rules checking before adding? Like checking port range or collisions?

- name: Debug firewall rules
  ansible.builtin.debug:
    var: _firewall_rules

- name: Process firewall rules added by other roles
  ansible.builtin.include_tasks: add_firewall_rule.yml
  loop: "{{ _firewall_rules }}"
  loop_control:
    loop_var: item
  when: _firewall_rules | length > 0

- name: Allow HTTPS connections
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
# 80 will be denied by default for all other sources
