---
- name: Ensure nftables is installed
  ansible.builtin.apt:
    name: nftables
  become: true

- name: Configure Firewall
  ansible.builtin.include_tasks: configure.yml

- name: Enable nftables
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: true
  become: true

- name: Record nftables status
  ansible.builtin.command: nft list ruleset
  become: true
  register: nftables_status
  changed_when: false

- name: Print nftables status
  ansible.builtin.debug:
    msg: "nftables status: {{ nftables_status.stdout }}"
  changed_when: false
